version: '3.8'

services:

  database:
    image: bitnami/postgresql:latest
    ports:
    - 5432:5432
    volumes:
      - .:/usr/src/database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: core-notes



